export const fullActionLibrary = [
  {
    id: 'w1',
    phase: 'Warm-up',
    pattern: 'Rotation',
    plane: 'Transverse',
    isNew: false,
    difficulty: 2,
    name: '翻书 (Open Book)',
    reg: '仰卧转体',
    instruct: '胸椎转动，呼气时把上侧肩膀慢慢打开。',
    sets: 2,
    reps: '10次/边',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'w2',
    phase: 'Warm-up',
    pattern: 'Squat',
    plane: 'Transverse',
    isNew: false,
    difficulty: 2,
    name: '90/90 髋切换',
    reg: '坐姿髋内外旋',
    instruct: '骨盆稳定，带动双髋顺畅切换，不要耸肩。',
    sets: 2,
    reps: '8次/边',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'w3',
    phase: 'Warm-up',
    pattern: 'Squat',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 1,
    name: '踝关节顶墙',
    reg: '跪姿踝背屈',
    instruct: '膝盖向前找墙，脚跟不离地，找脚踝活动度。',
    sets: 2,
    reps: '12次/边',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'w4',
    phase: 'Warm-up',
    pattern: 'Pull',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 2,
    name: '熊爬位后坐伸展',
    reg: '四点跪后坐',
    instruct: '手掌稳压地面，背阔肌发力，臀部往后找脚跟。',
    sets: 2,
    reps: '8次',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'w5',
    phase: 'Warm-up',
    pattern: 'Rotation',
    plane: 'Frontal',
    isNew: true,
    difficulty: 3,
    name: '跨步抱膝转髋',
    reg: '原地抱膝平衡',
    instruct: '控制髋部旋转，站稳后再换边。',
    sets: 2,
    reps: '6次/边',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'p1',
    phase: 'Power',
    pattern: 'Rotation',
    plane: 'Transverse',
    isNew: false,
    difficulty: 4,
    name: '药球侧抛',
    reg: '跪姿侧抛',
    instruct: '核心先锁住，髋部带动上肢，瞬间把球甩出去。',
    sets: 3,
    reps: '6次/边',
    restIntra: 45,
    restInter: 75,
  },
  {
    id: 'p2',
    phase: 'Power',
    pattern: 'Hinge',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 4,
    name: '跳箱落地稳定',
    reg: '原地快速下沉停住',
    instruct: '落地像静音一样，膝盖对齐脚尖，先稳再起。',
    sets: 3,
    reps: '4次',
    restIntra: 45,
    restInter: 75,
  },
  {
    id: 'p3',
    phase: 'Power',
    pattern: 'Push',
    plane: 'Sagittal',
    isNew: true,
    difficulty: 5,
    name: '跨步加速起动',
    reg: '分腿预备起动',
    instruct: '前脚踩实，身体前倾，第一步要快但不乱。',
    sets: 3,
    reps: '5次/边',
    restIntra: 45,
    restInter: 75,
  },
  {
    id: 's1',
    phase: 'Strength',
    pattern: 'Hinge',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 4,
    name: '单腿硬拉',
    reg: '支撑腿硬拉',
    instruct: '髋关节后移，脊柱保持长，脚底三点稳定发力。',
    sets: 3,
    weight: '12kg',
    reps: '8次/边',
    restIntra: 60,
    restInter: 75,
  },
  {
    id: 's2',
    phase: 'Strength',
    pattern: 'Squat',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 4,
    name: '前脚抬高分腿蹲',
    reg: '原地分腿蹲',
    instruct: '前脚全脚掌踩稳，躯干直立，后膝垂直向下。',
    sets: 3,
    weight: '10kg',
    reps: '8次/边',
    restIntra: 60,
    restInter: 75,
  },
  {
    id: 's3',
    phase: 'Strength',
    pattern: 'Pull',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 3,
    name: '单臂划船',
    reg: '胸撑划船',
    instruct: '肩胛先收紧，再把肘部拉向髋部。',
    sets: 3,
    weight: '14kg',
    reps: '10次/边',
    restIntra: 60,
    restInter: 75,
  },
  {
    id: 's4',
    phase: 'Strength',
    pattern: 'Push',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 3,
    name: '半跪地雷管推举',
    reg: '半跪哑铃推举',
    instruct: '骨盆和肋骨对齐，向前上方稳定推出。',
    sets: 3,
    weight: '15kg',
    reps: '8次/边',
    restIntra: 60,
    restInter: 75,
  },
  {
    id: 's5',
    phase: 'Strength',
    pattern: 'Squat',
    plane: 'Frontal',
    isNew: false,
    difficulty: 3,
    name: '侧弓步接单腿站立',
    reg: '原地侧弓步',
    instruct: '发力腿主动蹬地回收，站起时找髋部控制。',
    sets: 3,
    reps: '10次/边',
    restIntra: 60,
    restInter: 75,
  },
  {
    id: 's6',
    phase: 'Strength',
    pattern: 'Push',
    plane: 'Transverse',
    isNew: true,
    difficulty: 4,
    name: '俯卧撑支撑肩碰触',
    reg: '高位支撑肩碰触',
    instruct: '身体像一块板，碰肩时尽量不摇晃。',
    sets: 3,
    reps: '8次/边',
    restIntra: 60,
    restInter: 75,
  },
  {
    id: 'c1',
    phase: 'Core',
    pattern: 'Rotation',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 2,
    name: '死虫抗阻',
    reg: '基础死虫',
    instruct: '腰椎压地，对侧慢慢伸展，呼气时收紧核心。',
    sets: 3,
    reps: '30秒',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'c2',
    phase: 'Core',
    pattern: 'Rotation',
    plane: 'Transverse',
    isNew: false,
    difficulty: 3,
    name: 'Pallof 抗旋保持',
    reg: '半跪抗旋保持',
    instruct: '手把阻力推远后停住，不让躯干被带走。',
    sets: 3,
    reps: '20秒/边',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'c3',
    phase: 'Core',
    pattern: 'Pull',
    plane: 'Frontal',
    isNew: false,
    difficulty: 3,
    name: '侧桥抬腿',
    reg: '侧桥保持',
    instruct: '下侧腰不要塌，抬腿高度小而稳。',
    sets: 3,
    reps: '20秒/边',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'c4',
    phase: 'Core',
    pattern: 'Push',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 2,
    name: '中空呼吸',
    reg: '仰卧屈膝呼吸',
    instruct: '肋骨回收，鼻吸口呼，保持腹压稳定。',
    sets: 3,
    reps: '5次呼吸',
    restIntra: 20,
    restInter: 30,
  },
  {
    id: 'e1',
    phase: 'ESD',
    pattern: 'Push',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 3,
    name: '风阻车 30/30',
    reg: '自行车匀速踩',
    instruct: '30 秒提速，30 秒恢复，输出要平稳。',
    sets: 4,
    reps: '30秒',
    restIntra: 15,
    restInter: 25,
  },
  {
    id: 'e2',
    phase: 'ESD',
    pattern: 'Pull',
    plane: 'Sagittal',
    isNew: false,
    difficulty: 4,
    name: '划船机冲刺',
    reg: '中速划船',
    instruct: '腿髋手依次发力，回程保持节奏。',
    sets: 4,
    reps: '45秒',
    restIntra: 15,
    restInter: 25,
  },
  {
    id: 'e3',
    phase: 'ESD',
    pattern: 'Squat',
    plane: 'Frontal',
    isNew: false,
    difficulty: 3,
    name: '侧向滑步往返',
    reg: '原地侧向滑步',
    instruct: '重心放低，脚步快，膝盖保持对齐。',
    sets: 4,
    reps: '40秒',
    restIntra: 15,
    restInter: 25,
  },
  {
    id: 'e4',
    phase: 'ESD',
    pattern: 'Pull',
    plane: 'Sagittal',
    isNew: true,
    difficulty: 4,
    name: '农夫行走',
    reg: '轻负重行走',
    instruct: '肋骨下沉，握紧把手，小步快走。',
    sets: 4,
    weight: '16kg',
    reps: '20米',
    restIntra: 20,
    restInter: 30,
  },
]
